import createClient from "openapi-fetch";
import { afterAll, afterEach, beforeAll, expect, test, vi } from "vitest";
import type { paths } from "@cryptlex/web-api-types"; // generated by openapi-typescript
import { server } from "../../mock-server/node";
import { baseURL as MswBaseUrl } from "../../mock-server/handlers";
import { handleSubscriptionPaymentOverdue } from "../lib/eventHandlers/handleSubscriptionPaymentOverdue";

beforeAll(() => {
  // NOTE: server.listen must be called before `createClient` is used to ensure
  // the msw can inject its version of `fetch` to intercept the requests.
  server.listen({
    onUnhandledRequest: (request) => {
      throw new Error(
        `No request handler found for ${request.method} ${request.url}`
      );
    },
  });
});

afterEach(() => server.resetHandlers());
afterAll(() => server.close());

test("Handle Order Completed flow", async () => {
  const client = createClient<paths>({
    baseUrl: MswBaseUrl,
  });

  await handleSubscriptionPaymentOverdue(client, {"id":"qwerty",
    "data": {
    "id": "To4TBBJfRSGlNLsJ2dL2sg",
    "quote":"QUOT2J52LKCFCHPOYSW6UTRMNZJA",
    "subscription": "To4TBBJfRSGlNLsJ2dL2sg",
    "active": true,
    "state": "overdue",
    "changed": 1585936267665,
    "changedValue": 1585936267665,
    "changedInSeconds": 1585936267,
    "changedDisplay": "4/3/20",
    "live": false,
    "currency": "USD",
    "account": {
      "id": "gB_slATyQBqSpAxA7-1YAg",
      "account": "gB_slATyQBqSpAxA7-1YAg",
      "contact": {
        "first": "John",
        "last": "Doe",
        "email": "ne1@all.com",
        "company": null,
        "phone": null
      },
      "language": "en",
      "country": "US",
      "lookup": {
        "global": "VKMqlZ--TIuD44BvXdNkbg"
      },
      "url": "https://yourexamplestore.onfastspring.com/account"
    },
    "product": {
      "product": "example-subscription-monthly",
      "parent": null,
      "display": {
        "en": "Example Subscription - Monthly"
      },
      "description": {
        "summary": {
          "en": "This is the **Summary** description for Example Subscription - Monthly."
        },
        "action": {
          "en": "Buy Now"
        },
        "full": {
          "en": "This is the **Long Description** for Example Subscription - Monthly."
        }
      },
      "image": "https://d8y8nchqlnmka.cloudfront.net/p31bZYrcQUs/_CW0gCU8SR0/example-subscription-monthly_256.png",
      "sku": "SKU1234",
      "fulfillments": {
        "instructions": {
          "en": "Thank you for subscribing to _Example Subscription Monthly_. Please download the installer file using the button or link found on this page. Your license key is also displayed here."
        },
        "example-subscription-monthly_email_0": {
          "fulfillment": "example-subscription-monthly_email_0",
          "name": "Email (Your #{orderItem.display} Deli...)",
          "applicability": "NON_REBILL_ONLY"
        },
        "example-subscription-monthly_file_0": {
          "fulfillment": "example-subscription-monthly_file_0",
          "name": "File Download (Example.pdf)",
          "applicability": "NON_REBILL_ONLY",
          "display": null,
          "url": null,
          "size": null,
          "behavior": "PREFER_EXPLICIT",
          "previous": []
        },
        "example-subscription-monthly_license_0": {
          "fulfillment": "example-subscription-monthly_license_0",
          "name": "License Generator (Pre-defined List)",
          "applicability": "NON_REBILL_ONLY"
        },
        "example-subscription-monthly_license_1": {
          "fulfillment": "example-subscription-monthly_license_1",
          "name": "Signed PDF Generator (Example Fulfillment File.pdf)",
          "applicability": "NON_REBILL_ONLY"
        }
      },
      "format": "digital",
      "pricing": {
        "trial": 7,
        "interval": "month",
        "intervalLength": 1,
        "intervalCount": null,
        "quantityBehavior": "allow",
        "quantityDefault": 1,
        "price": {
          "USD": 30
        },
        "dateLimitsEnabled": false,
        "reminderNotification": {
          "enabled": true,
          "interval": "week",
          "intervalLength": 1
        },
        "overdueNotification": {
          "enabled": true,
          "interval": "week",
          "intervalLength": 1,
          "amount": 1
        },
        "cancellation": {
          "interval": "week",
          "intervalLength": 1
        }
      }
    },
    "sku": "SKU1234",
    "display": "Example Subscription - Monthly",
    "quantity": 2,
    "adhoc": false,
    "autoRenew": true,
    "price": 30,
    "priceDisplay": "$30.00",
    "priceInPayoutCurrency": 30,
    "priceInPayoutCurrencyDisplay": "$30.00",
    "discount": 0,
    "discountDisplay": "$0.00",
    "discountInPayoutCurrency": 0,
    "discountInPayoutCurrencyDisplay": "$0.00",
    "subtotal": 60,
    "subtotalDisplay": "$60.00",
    "subtotalInPayoutCurrency": 60,
    "subtotalInPayoutCurrencyDisplay": "$60.00",
    "next": 1591747200000,
    "nextValue": 1591747200000,
    "nextInSeconds": 1591747200,
    "nextDisplay": "6/10/20",
    "end": null,
    "endValue": null,
    "endInSeconds": null,
    "endDisplay": null,
    "canceledDate": null,
    "canceledDateValue": null,
    "canceledDateInSeconds": null,
    "canceledDateDisplay": null,
    "deactivationDate": null,
    "deactivationDateValue": null,
    "deactivationDateInSeconds": null,
    "deactivationDateDisplay": null,
    "sequence": 3,
    "periods": null,
    "remainingPeriods": null,
    "begin": 1585872000000,
    "beginValue": 1585872000000,
    "beginInSeconds": 1585872000,
    "beginDisplay": "4/3/20",
    "intervalUnit": "month",
    "intervalLength": 1,
    "nextChargeCurrency": "USD",
    "nextChargeDate": 1591747200000,
    "nextChargeDateValue": 1591747200000,
    "nextChargeDateInSeconds": 1591747200,
    "nextChargeDateDisplay": "6/10/20",
    "nextChargePreTax": 60,
    "nextChargePreTaxDisplay": "$60.00",
    "nextChargePreTaxInPayoutCurrency": 60,
    "nextChargePreTaxInPayoutCurrencyDisplay": "$60.00",
    "nextChargeTotal": 60,
    "nextChargeTotalDisplay": "$60.00",
    "nextChargeTotalInPayoutCurrency": 60,
    "nextChargeTotalInPayoutCurrencyDisplay": "$60.00",
    "nextNotificationType": "PAYMENT_OVERDUE",
    "nextNotificationDate": 1592352000000,
    "nextNotificationDateValue": 1592352000000,
    "nextNotificationDateInSeconds": 1592352000,
    "nextNotificationDateDisplay": "6/17/20",
    "trialReminder": {
      "intervalUnit": "day",
      "intervalLength": 3
    },
    "paymentReminder": {
      "intervalUnit": "week",
      "intervalLength": 1
    },
    "paymentOverdue": {
      "intervalUnit": "week",
      "intervalLength": 1,
      "total": 1,
      "sent": 0
    },
    "cancellationSetting": {
      "cancellation": "AFTER_LAST_NOTIFICATION",
      "intervalUnit": "week",
      "intervalLength": 1
    },
    "fulfillments": {
      "example-subscription-monthly_license_0": [
        {
          "license": "dOvOkW4iomHjTYk4aN7K",
          "display": "License Key",
          "type": "license"
        }
      ],
      "example-subscription-monthly_file_0": [
        {
          "display": "Example.pdf",
          "size": 224143,
          "file": "https://yourexamplestore.onfastspring.com/account/file/YOU200403-5980-53325F",
          "type": "file"
        }
      ],
      "example-subscription-monthly_license_1": [
        {
          "display": "Example Fulfillment File.pdf",
          "size": 325134,
          "file": "https://yourexamplestore.onfastspring.com/account/file/YOU200403-5980-60306L",
          "type": "file"
        }
      ],
      "instructions": "Thank you for subscribing to Example Subscription Monthly. Please download the installer file using the button or link found on this page. Your license key is also displayed here."
    },
    "instructions": [
      {
        "product": "example-subscription-monthly",
        "type": "regular",
        "periodStartDate": null,
        "periodStartDateValue": null,
        "periodStartDateInSeconds": null,
        "periodStartDateDisplay": null,
        "periodEndDate": null,
        "periodEndDateValue": null,
        "periodEndDateInSeconds": null,
        "periodEndDateDisplay": null,
        "intervalUnit": "month",
        "intervalLength": 1,
        "discountPercent": 0,
        "discountPercentValue": 0,
        "discountPercentDisplay": "0%",
        "discountTotal": 0,
        "discountTotalDisplay": "$0.00",
        "discountTotalInPayoutCurrency": 0,
        "discountTotalInPayoutCurrencyDisplay": "$0.00",
        "unitDiscount": 0,
        "unitDiscountDisplay": "$0.00",
        "unitDiscountInPayoutCurrency": 0,
        "unitDiscountInPayoutCurrencyDisplay": "$0.00",
        "price": 30,
        "priceDisplay": "$30.00",
        "priceInPayoutCurrency": 30,
        "priceInPayoutCurrencyDisplay": "$30.00",
        "priceTotal": 60,
        "priceTotalDisplay": "$60.00",
        "priceTotalInPayoutCurrency": 60,
        "priceTotalInPayoutCurrencyDisplay": "$60.00",
        "unitPrice": 30,
        "unitPriceDisplay": "$30.00",
        "unitPriceInPayoutCurrency": 30,
        "unitPriceInPayoutCurrencyDisplay": "$30.00",
        "total": 60,
        "totalDisplay": "$60.00",
        "totalInPayoutCurrency": 60,
        "totalInPayoutCurrencyDisplay": "$60.00"
      }
    ]
  }
});
});
